# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Just Arrived
email: hej@justarrived.se
description: > # this means to ignore newlines until "baseurl:"
  Helping newcomers in Sweden enter the labor market.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://justarrived.se" # the base hostname & protocol for your site
twitter_username: justarrivedse
github_username:  justarrived
exclude: ["LICENSE", "README.md", "Gemfile", "Gemfile.lock", ".editorconfig", "script/", "CNAME", "Gruntfile.js", "package.json", "node_modules/", "npm-shrinkwrap.json"]
permalink: pretty

facebook_url: https://www.facebook.com/JustArrivedSE
twitter_url: https://twitter.com/justarrivedse
instagram_url: https://www.instagram.com/justarrivedse/
linkedin_url: https://www.linkedin.com/company/just-arrived-sweden
github_urlL: https://github.com/justarrived

app_signin_link: https://app.justarrived.se/#/user/signin

wintrgarden_signup_no_reg: https://wgtrm.com/dc/#justarrived.jaas1
wintrgarden_signup_reg: https://wgtrm.com/dc/#justarrived.jar2

# "App" settings
job_submission_email: 'anna.hornmark+company-forms@justarrived.se'
job_submission_redirect_url: 'http://justarrived.se/thanks/job-submit'

company_submission_redirect_url: http://justarrived.se/thanks/company-register-submit

contact_email: hej@justarrived.se

# analytic keys
segment_key: Im5TEqG2121n8lVHvgwNAW9yQ42j69Nd
fb_key: 1166436026729850

# Build settings
markdown: kramdown
# theme: minima
sass:
    sass_dir: assets/sass
    style: compressed

# Plugins
gems:
  - jekyll-multiple-languages-plugin
  - octopress-paginate

# octopress-paginate config
pagination:
  limit: false
  per_page: 3
  title_suffix: " (page :num)"

# I18n
rtl_languages: ["ar"]

# I18n plugin: jekyll-multiple-languages-plugin
languages: ["en", "sv", "ar"]
exclude_from_localizations: ["assets", "favicon.ico", "_posts"]

# Blog
authors:
  buren:
    display_name: Jacob Burenstam
    email: jacob@justarrived.se
    web: http://jacobburenstam.com/
    twitter: jacobburenstam
    github: buren
